apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: default
spec:
  secretName: app-tls
  duration: 2160h
  renewBefore: 360h
  commonName: app.example.com
  dnsNames:
  - app.example.com
  issuerRef:
    name: nwb-workspace-ca-issuer
    kind: ClusterIssuer
